steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west6-docker.pkg.dev/${PROJECT_ID}/${_REGISTRY_NAME}/${_IMAGE_NAME}:${TAG_NAME}', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west6-docker.pkg.dev/${PROJECT_ID}/${_REGISTRY_NAME}/${_IMAGE_NAME}:${TAG_NAME}']
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
  logging: CLOUD_LOGGING_ONLY

